version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_capitole
    environment:
      POSTGRES_DB: capitole_db
      POSTGRES_USER: capitole_user
      POSTGRES_PASSWORD: capitole_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productsApi
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/capitole_db
      SPRING_DATASOURCE_USERNAME: capitole_user
      SPRING_DATASOURCE_PASSWORD: capitole_pass
    depends_on:
      - postgres

volumes:
  postgres_data: